name: Main Nginx Action

on:
  push:
    branches: [ "master" ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bulild and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}
          push: true
      
